"""Add Invitation table

Revision ID: 4510f05ca42a
Revises: 
Create Date: 2025-01-25 11:12:08.817325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4510f05ca42a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_user', sa.Integer(), nullable=True),
    sa.Column('consumed_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consumed_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    # ### end Alembic commands ###
